#!/bin/sh

read -r -d '' USAGE << EOM
Usage:
    tigerc <file> <task> [argument] [options...]

Tasks:
    --parse-tree        Generates a representation of the input program's parse tree

Options:
    -h, --help          Show this message
    --color             Turns on colored output (default=true)
    --no-color          Turns off colored output
EOM

COLOR=1;

error() {
    MESSAGE=$1;
    if [[ COLOR -eq 1 ]]; then
        echo -e "\x1b[1m\x1b[31m[ERROR]\x1b[0m $MESSAGE";
    else
        echo "[ERROR] $MESSAGE";
    fi
    exit 1;
}

if [[ "$#" -lt 1 ]]; then
    echo "$USAGE";
    exit 0;
else
    TARGET=$1;
    shift;
fi

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help) echo "$USAGE"; exit 0;;
        --color) COLOR=1;;
        --no-color) COLOR=0;;
        --parse-tree) MODE="tree";;
        *) error "Unknown option '$1'" ;;
    esac
    shift
done

if [[ ! -f $TARGET ]]; then
    error "The file $TARGET does not exist.";
fi

case $MODE in
    tree) ./gradlew -q --console plain --init-script init.gradle tree -PinFile=$TARGET -Pcolor=$COLOR ;;
    *) ./gradlew -q --console plain --init-script init.gradle run -Pcolor=$COLOR;;
esac